steps:
  - name: requirements
    image: composer
    commands:
    - composer install --no-dev
  - name: run
    image: php:cli-bookworm
    commands:
      - php examples/3teams.php
      - php examples/basic.php
  - name: dependencies
    image: composer
    commands:
    - composer install
    - vendor/bin/phpunit tests --no-coverage